skill.id: [SKILL ID]
server:
  port: 8443
  http2:
    enabled: true
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
  ssl:
    key-store: [KEYSTORE LOCATION]
    key-store-password: [PASSWORD]
    keyStoreType: PKCS12
    key-alias: tomcat
